import { builtinModules } from 'node:module';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD.
See the plugin repository for source code.
*/
`;

export function createBuildOptions({ outfile, production }) {
	return {
		banner: {
			js: banner,
		},
		entryPoints: ['src/main.ts'],
		bundle: true,
		external: [
			'obsidian',
			'electron',
			'@codemirror/autocomplete',
			'@codemirror/collab',
			'@codemirror/commands',
			'@codemirror/language',
			'@codemirror/lint',
			'@codemirror/search',
			'@codemirror/state',
			'@codemirror/view',
			'@lezer/common',
			'@lezer/highlight',
			'@lezer/lr',
			...builtinModules,
		],
		format: 'cjs',
		target: 'es2021',
		loader: {
			'.wasm': 'dataurl',
		},
		logLevel: 'info',
		sourcemap: production ? false : 'inline',
		treeShaking: true,
		outfile,
		minify: production,
	};
}
