import type { Locale } from '@embedpdf/plugin-i18n';

export const ZH_CN_LOCALE: Locale = {
	code: 'zh-CN',
	name: '简体中文',
	translations: {
		commands: {
			zoom: {
				in: '放大',
				out: '缩小',
				fitWidth: '适合宽度',
				fitPage: '适合页面',
				automatic: '自动缩放',
				level: '缩放比例（{level}%）',
				inArea: '框选放大',
			},
			fullscreen: {
				enter: '进入全屏',
				exit: '退出全屏',
			},
			rotate: {
				clockwise: '顺时针旋转',
				counterclockwise: '逆时针旋转',
			},
			menu: '菜单',
			sidebar: '侧边栏',
			search: '搜索',
			comment: '评论',
			download: '下载',
			print: '打印',
			openFile: '打开 PDF',
			save: '保存',
			settings: '设置',
			view: '阅读',
			annotate: '标注',
			shapes: '形状',
			redact: '涂黑',
			fillAndSign: '填写与签名',
			form: '表单',
			pan: '拖拽',
			pointer: '选择',
			undo: '撤销',
			redo: '重做',
			copy: '复制',
			screenshot: '截图',
			nextPage: '下一页',
			previousPage: '上一页',
		},
	},
};
